fixed file for homework #1
Ttiimmii/Python_Course pull request #2
Opened 2021-03-23 09:23 UTC by Ttiimmii

2021-03-23 19:35 UTC, zhidelev requested changes

2021-03-23 19:35 UTC, zhidelev commented on Lecture_1_Introduction_homework/test_sample.py
> +    return test_string.replace(" ", "").replace("\t", "")
Привет, вариант рабочий, но лучше использовать ```strip()``` - тесты тоже проходят, а код лаконичней. Поменяй, пожалуйста на ```strip()``` и ДЗ приму 👍

2021-03-24 07:36 UTC, Ttiimmii commented on Lecture_1_Introduction_homework/test_sample.py
> +    return test_string.replace(" ", "").replace("\t", "")
Привет, сделал выбор в пользу чейн-реплейсов потому что:
1. ориентрировался на выкладки [отсюда](https://stackoverflow.com/questions/3939361/remove-specific-characters-from-a-string-in-python), судя по перформансу это лучшее решение, хотя визуально и правда так себе
2. Метод называется remove_spaces и мы можем не знать, где находятся пробельные символы, поэтому отказался от решщения со strip(), т.к. оно бы сужало внутреннюю логику.

На основе вышеописанного требуется ли переделать дз или нет?

2021-03-24 07:57 UTC, zhidelev commented on Lecture_1_Introduction_homework/test_sample.py
> +    return test_string.replace(" ", "").replace("\t", "")
Ок, понял, я обновлю ДЗ для следующих групп, чтобы было понятней. Тогда мерджи, лучше уже сфокусироваться на втором ДЗ, которое скоро выложат 👍

2021-03-24 07:57 UTC, zhidelev approved these changes

2021-03-24 08:49 UTC, merged